flush_with_reason
inhabitedtype/faraday pull request #68
Opened 2021-06-25 10:20 UTC by dhouse-js

Adds a new function to the interface, ``flush_with_reason : t -> ([ `Shift | `Drain ] -> unit) -> unit``, which is like `flush` but it gives the callback information on why it is being called.

2021-07-05 20:37 UTC, seliopou requested changes

2021-07-05 20:37 UTC, seliopou commented on lib/faraday.mli
> +val flush_with_reason : t -> ([ `Shift | `Drain | `Nothing_pending ] -> unit) -> unit
How about a regular variant instead?

2021-07-08 12:49 UTC, dhouse-js commented on lib/faraday.mli
> +val flush_with_reason : t -> ([ `Shift | `Drain | `Nothing_pending ] -> unit) -> unit
Done

2021-07-09 09:15 UTC, dhouse-js commented on lib/faraday.mli
> +val flush_with_reason : t -> ([ `Shift | `Drain | `Nothing_pending ] -> unit) -> unit
Done.

2021-07-10 19:34 UTC, seliopou approved these changes

2021-07-11 03:12 UTC, merged